- name: template
  ansible.builtin.template:
    src: ../../files/collect.sh.j2
    dest: /tmp/collect.sh
    mode: "0755"
  environment:
    ISUCON_DB_NAME: "{{ ISUCON_DB_NAME }}"
    ISUCON_DB_USER: "{{ ISUCON_DB_USER }}"
    ISUCON_DB_PASSWORD: "{{ ISUCON_DB_NAME }}"
  ignore_errors: true

- name: shell
  shell: bash /tmp/collect.sh | tee /tmp/collect.log
  register: result
  changed_when: false
- name: show stdout
  debug:
    msg: "{{ result.stdout_lines }}"

- name: remove file
  file:
    path: /tmp/collect.sh
    state: absent

- name: fetch service
  ansible.builtin.fetch:
    src: /tmp/collect.log
    dest: ../files/fetch/collect.log
    flat: true
  ignore_errors: true
