- name: Purge the package "needrestart"
  apt:
    name: needrestart
    state: absent
    purge: true
    autoremove: true

- name: Update Upgrade
  apt:
    upgrade: false
    update_cache: true

- name: set inputrc
  lineinfile:
    dest: /etc/inputrc
    insertafter: EOF
    line: "{{ item }}"
  with_items:
    - "set bell-style none"

- name: Change hostname
  hostname:
    name: "{{ inventory_hostname }}"
  ignore_errors: true

- name: Update /etc/hosts with new hostname and additional lines
  blockinfile:
    path: /etc/hosts
    block: |
      {{ ISU1_IP }} {{ ISU1_HOSTNAME }}
      {{ ISU2_IP }} {{ ISU2_HOSTNAME }}
      {{ ISU3_IP }} {{ ISU3_HOSTNAME }}
    state: present
  ignore_errors: true
#
# - name: Update /etc/hosts with new hostname and additional lines
#   blockinfile:
#     path: /etc/hosts
#     block: |
#       {{ hostvars['isu1']['ansible_host'] }} {{ ISU1_HOSTNAME }}
#       {{ hostvars['isu2']['ansible_host'] }} {{ ISU2_HOSTNAME }}
#       {{ hostvars['isu3']['ansible_host'] }} {{ ISU3_HOSTNAME }}
#     state: present
#   ignore_errors: true
