- name: Install the package
  apt:
    name:
      - mysqltuner

- name: Copy
  copy:
    src: ../../files/mysql/my.cnf
    dest: /etc/mysql/my.cnf
    mode: "0644"

- name: set
  lineinfile:
    dest: /lib/systemd/system/mysql.service
    backrefs: true
    insertafter: EOF
    regexp: '^#?\s*LimitNOFILE='
    line: "LimitNOFILE=65535"
  ignore_errors: yes

- name: remove file
  file:
    path: /var/log/mysql/mysql-slow.log
    state: absent

- name: shell
  shell: mysql -u root -p{{ ISUCON_DB_PASSWORD }} -e "CREATE USER '{{ ISUCON_DB_USER }}'@'%' IDENTIFIED BY '{{ ISUCON_DB_NAME }}';"
  ignore_errors: yes

- name: shell
  shell: mysql -u root -p{{ ISUCON_DB_PASSWORD }} -e "GRANT ALL PRIVILEGES ON *.* TO '{{ ISUCON_DB_USER }}'@'%' WITH GRANT OPTION;"
  ignore_errors: yes

- name: shell
  shell: mysql -u root -p{{ ISUCON_DB_PASSWORD }} -e "flush privileges;"
  ignore_errors: yes

- name: mysql is restarted
  systemd:
    name: mysql
    state: restarted
  become: yes
