# https://repo.netdata.cloud/repos/stable/ubuntu/noble/netdata_1.47.4%2Bubuntu24.04_amd64.deb

- name: Install the package
  apt:
    name:
      - netdata

- name: set netdata.conf
  lineinfile:
    dest: /etc/netdata/netdata.conf
    backrefs: true
    insertafter: EOF
    regexp: '^#?\s*bind socket to IP'
    line: "bind socket to IP = 0.0.0.0"
  ignore_errors: true

# ダッシュボード機能が使えないのでコメントアウト
# - name: Copy html
#   become: true
#   ansible.builtin.copy:
#     src: ../../files/netdata/isucon.html
#     dest: /var/lib/netdata/www/isucon.html
#     mode: "0644"

- name: netdata is running
  systemd:
    name: netdata
    state: started
    enabled: true
  ignore_errors: true

- name: netdata is restarted
  systemd:
    name: netdata
    state: restarted
  ignore_errors: true
